name: gmo-checkin
on:
  schedule:
  # 7GMT+7 → 0UTC
    - cron: '00 0 * * 1-5'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkin
        run: |
          curl --request POST 'https://checkin.runsystem.info/attendance/submit' \
          --header 'Content-Type: application/json' \
          --header 'Cookie: ${{ secrets.GMO_CHECKIN_AUTH }}' \
          --data-raw '{
              "type": "checkin",
              "emoji": 3,
              "comment": ""
          }'
